### ISSUE TITLE
Block not visible when page editing off in Totara 11

### ISSUE THREAD

**Issue by logan-reynolds** [gautamdas130780/moodle_block_mynotes#1] opened 2019-02-14 22:03 UTC
After installing the plugin on Totara 11 (which is based on Moodle 3.2) the block appears in the upper left of page, however once you click "Turn editing off" to go back to regular page view the block is no longer visible.  Checked permissions and I believe all users should be able to see it, since moodle/block:view is available to the Authenticated user role.

**Comment by jddjasdip** [comment] 2019-02-14 22:15
New info:  In the Site Admin Plugin Settings for My Notes, I changed the  last setting at to be “lower right” and now when I turn off editing at the page, the My Notes icon appears as it should in the lower right, however it is not hot, nothing happens when I click it.   It's basically just displaying as a plain image and has no href link or action attached to it, so does nothing.  So it is still not working.

**Comment by gautamdas130780** [comment] 2019-03-01 06:20
> New info: In the Site Admin Plugin Settings for My Notes, I changed the last setting at to be “lower right” and now when I turn off editing at the page, the My Notes icon appears as it should in the lower right, however it is not hot, nothing happens when I click it. It's basically just displaying as a plain image and has no href link or action attached to it, so does nothing. So it is still not working.

Hi, Sorry for late reply. have you faced this issue with any other theme or specific theme? In my opinion, you can test with moodle (clean theme or more theme). If that issue will not be solved then I will try to solve your problem / issue.

**Comment by ghost** [comment] 2019-03-02 02:55
Thank you; in rechecking on the core Totara Basis theme this does seem to be working fine in that case.  I'll followup to determine if this error was maybe due to the particular theme in use or some other setting on the site in question.  Closing as non-reproducible on the default theme.

**Closed as completed by ghost** 2019-03-02 02:55 UTC
